site:
  title: Dev Center Docs
  start_page: home::index.adoc
content:
  sources:
    - url: https://github.com/the-dev-center/docs.git
      branches: HEAD
      start_path: docs
    - url: https://github.com/the-dev-center/dev-center.git
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: Z:/code/amdphreak/antora-ui-default/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
