site:
  title: Dev Center Docs (Local)
  start_page: home::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../dev-center
      branches: HEAD
      start_path: docs
      worktrees: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./build/site
asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''
