site:
  title: Dev Center Docs (Local)
  start_page: home::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../dev-center
      branches: HEAD
      start_path: docs
      worktrees: true
      exclude:
        - "**/node_modules/**"
        - "site/**"
        - "**/build/**"
        - ".pnpm-store/**"
ui:
  bundle:
    url: https://gitlab.com/the-dev-center/antora-dark-theme/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./build/site
asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''
