site:
  title: Dev Center Docs (Local)
  start_page: home::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../dev-center
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../antora-dark-theme
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../antora-demo-template
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../antora-extensions-registry
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../antora-themes-site
      branches: HEAD
      start_path: docs
      worktrees: true
    - url: ../templates
      branches: HEAD
      start_path: docs
      worktrees: true
ui:
  bundle:
    url: https://gitlab.com/the-dev-center/antora-dark-theme/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./build/site
asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''
